final List<Map<String, dynamic>> array1 = [
  {"id": 1, "path": "assets/images/bukhari/1.json"},
  {"id": 1, "path": "assets/images/bukhari/2.json"},
  {"id": 1, "path": "assets/images/bukhari/3.json"},
  {"id": 1, "path": "assets/images/bukhari/4.json"},
  {"id": 1, "path": "assets/images/bukhari/5.json"},
  {"id": 1, "path": "assets/images/bukhari/6.json"},
  {"id": 1, "path": "assets/images/bukhari/7.json"},
  {"id": 1, "path": "assets/images/bukhari/8.json"},
  {"id": 1, "path": "assets/images/bukhari/9.json"},
  {"id": 1, "path": "assets/images/bukhari/10.json"},
  {"id": 1, "path": "assets/images/bukhari/11.json"},
  {"id": 1, "path": "assets/images/bukhari/12.json"},
  {"id": 1, "path": "assets/images/bukhari/13.json"},
  {"id": 1, "path": "assets/images/bukhari/14.json"},
  {"id": 1, "path": "assets/images/bukhari/15.json"},
  {"id": 1, "path": "assets/images/bukhari/16.json"},
  {"id": 1, "path": "assets/images/bukhari/17.json"},
  {"id": 1, "path": "assets/images/bukhari/18.json"},
  {"id": 1, "path": "assets/images/bukhari/19.json"},
  {"id": 1, "path": "assets/images/bukhari/20.json"},
  {"id": 1, "path": "assets/images/bukhari/21.json"},
  {"id": 1, "path": "assets/images/bukhari/22.json"},
  {"id": 1, "path": "assets/images/bukhari/23.json"},
  {"id": 1, "path": "assets/images/bukhari/24.json"},
  {"id": 1, "path": "assets/images/bukhari/25.json"},
  {"id": 1, "path": "assets/images/bukhari/26.json"},
  {"id": 1, "path": "assets/images/bukhari/27.json"},
  {"id": 1, "path": "assets/images/bukhari/28.json"},
  {"id": 1, "path": "assets/images/bukhari/29.json"},
];

final List<Map<String, dynamic>> array2 = [
  {"id": 2, "path": "assets/images/bukhari/4.json"},
  {"id": 2, "path": "assets/images/bukhari/5.json"},
];
